name: API tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository # Клонируем репозиторий
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Clone test server repository
        run: git clone https://github.com/Nikita-Filonov/qa-automation-engineer-api-course.git

      - name: Install test server dependencies
        run: pip install -r qa-automation-engineer-api-course/requirements.txt

      - name: Start a test server
        env:
          APP_HOST: "http://localhost:8000"  # Устанавливаем адрес хоста сервера
          DATABASE_URL: "sqlite+aiosqlite:///./local.db" # Устанавливаем URL локальной базы данных
          JWT_ALGORITHM: "HS256" # Алгоритм для JWT токенов
          JWT_SECRET_KEY: "qa-automation-engineer-api-course-secret-key" # Секретный ключ для JWT
          JWT_ACCESS_TOKEN_EXPIRE: 1800 # Время жизни access token (в секундах)
          JWT_REFRESH_TOKEN_EXPIRE: 5184000 # Время жизни refresh token (в секундах)
        run: uvicorn main:app --host 0.0.0.0 --port 8000 --app-dir ./qa-automation-engineer-api-course &


      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          

      - name: Run test with Pytest and generate Allure result
        run: |
          pytest -m regression --alluredir=allure-results --numprocesses 2

      - name: Archive test artefacts
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: allure-result



  publish-report:
    runs-on: ubuntu-latest
    needs: run_tests
    steps:
      - name: Check out repository # Клонируем репозиторий
        uses: actions/checkout@v6
      - name: Download test-results
        uses: actions/download-artifact@v5
        with:
          name: test-results

      - name: Get Allure history
        uses: actions/checkout@v6
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages


      - name: Generates Allure Report with history
        uses: simple-elf/allure-report-action@v1.13
        if: always()
        with:
          allure_results: allure-results
          allure_history: allure-history

      - name: Deploy report to Github pages
        if: always()
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history





